'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Dosis } from "next/font/google";
import { useState } from "react";
import AppProvider from "./components/AppProvider";
const dosis_init = Dosis ({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-dosis'
})
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [activeBtn, setActiveBtn] = useState(-1);
  return (
    <html lang="en">
      <body className={clsx(inter.className, dosis_init.variable)}>
      <svg
                    
                    width="0" height="0">
                        <linearGradient id="gradientStroke" x1="0%" y1="0%" x2="100%" y2="100%">
                            <stop offset="0%" style={{ stopColor: '#FFB9D2', stopOpacity: 1 }} />
                            <stop offset="100%" style={{ stopColor: '#BB9BFF', stopOpacity: 1 }} />
                        </linearGradient>
                        </svg>
      <AppProvider activeBtn={activeBtn} setActiveBtn={setActiveBtn}>
        {children}
      </AppProvider> 
        </body>
    </html>
  );
}
